---
- name: Create service file
  template:
    dest: "/etc/systemd/system/{{ container_service_name }}"
    src: "systemd-container.service"
  register: service_config
  become: yes

- name: Reload daemon
  shell: systemctl daemon-reload
  when: service_config.changed
  become: yes

- name: Restart service
  service:
    name: "{{ container_service_name }}"
    state: restarted
  when: service_config.changed
  become: yes

- name: Enable service
  service:
    name: "{{ container_service_name }}"
    state: started
    enabled: yes
  become: yes
